{% set name = "gcloud-aio-pubsub" %}
{% set version = "5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcloud_aio_pubsub-{{ version }}.tar.gz
  sha256: 6a93fa55323d04cdbd1df48564b1c2e0cc1273d995222747546a3776c49b55a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4.0
    - gcloud-aio-auth >=3.3.0,<5.0.0
    - prometheus_client >=0.13.1,<1.0.0
    - setuptools >=66.0.0,<67.0.0

test:
  imports:
    - gcloud.aio.pubsub
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Pub/Sub
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
