{% set name = "gcloud-aio-pubsub" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcloud_aio_pubsub-{{ version }}.tar.gz
  sha256: 72146a0573ff7c69cdb9d31f79701588105ddc0383e663d4b49b148786fc0819

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - gcloud-aio-auth >=3.3.0,<6.0.0
    - prometheus_client >=0.13.1,<1.0.0

test:
  imports:
    - gcloud.aio.pubsub
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Pub/Sub
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
