{% set name = "gcloud-aio-pubsub" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gcloud_aio_pubsub-{{ version }}.tar.gz
  sha256: 5713d11077a497ef3efcdae73b682b6058a60c5c697485a4c52790d0e183e540

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - gcloud-aio-auth >=3.3.0,<6.0.0
    - prometheus_client >=0.13.1,<1.0.0

test:
  imports:
    - gcloud.aio.pubsub
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Pub/Sub
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
